#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 
bspc config border_width         2
bspc config window_gap           2
bspc config top_padding          30
bspc rule -a Zathura state=tiled
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
xsettingsd& # manage GTK themes
wmname LG3D # for java/netbeans
#AutoStart applications
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh &
nm-applet &
nextcloud &
darkman run &

